### ISSUE TITLE
Add Change Theme option.

### ISSUE THREAD

**Issue by pandeyganesha** [pandeyganesha/digit-dare#1]
Add light or dark theme option
Or we can add a complete menu for different types of theme that user can switch between.

**Comment by ngothuythanhtam** [comment]
Hi @pandeyganesha , could you please assign this issue to me? I'd like to work on it. Thank you!

**Comment by pandeyganesha** [comment]
@ngothuythanhtam 
Feel free to discuss the design. We can do it in two stages.
1. Giving a small theme icon which toggles between light and dark theme when pressed.
2. Or we can create a dropdown where we provide many themes

**Comment by ngothuythanhtam** [comment]
@pandeyganesha Thanks for sharing your ideas! Both options sound great. I think starting with the small theme icon that toggles between light and dark modes would be a simple and user-friendly approach , and we can always add the dropdown for more themes later if users request it.
Would you prefer focusing on the icon toggle first or should we explore the dropdown option right away?

**Comment by pandeyganesha** [comment]
@ngothuythanhtam No issues
proceed as you feel better. I am ok with toggle button first. 
Here is my question, share your thoughts

Should we place that toggle button in some corner (left, right, up, down) or should we create a navigation bar / header and place that toggle button there? You may proceed as you prefer. But I personally was thinking to make this site look little different by not adding that top menu. Making the design little different.

Also please animate the theme change when toggle button hi pressed, like some ripple effect.

**Comment by ngothuythanhtam** [comment]
@pandeyganesha 
Regarding its placement, I think integrating it into a navigation bar/header would provide a cleaner and more intuitive user experience, especially if we plan to expand the theme options later on. As for the ripple effect animation, that sounds like a fun touch! I'll go ahead with that and ensure the theme change feels smooth and engaging. I'll proceed with these ideas and keep you updated!

**Comment by pandeyganesha** [comment]
@ngothuythanhtam 
Ok No issues. Do it. Thanks

**Comment by pandeyganesha** [comment]
@ngothuythanhtam 
I just thought it now. We will also integrating difficulty levels in the game.

So for that we will be making a game menu that pops up in center when we load the website.
So we can use that pop up to adjust the settings like theme toggle or select level or taking username anything like that.

Let's treat it like a game only not like website.
Let's not create navigation bar and create a pop up menu. We already have that pop up but it currently shows Game Rules. ( you can check it out)

We can replace that with game menu where we can add theme toggle option, levels, may be sounds effect options and so on.

Sorry for updating my design like this. But I got better picture in my head now.
Let's proceed this way please.

Let me know your thoughts on this.

**Comment by pandeyganesha** [comment]
@ngothuythanhtam We have got another contributor who is working on Game Levels. 
He will be making the menu.

You please create the theme toggle button in such a way that we can easily move your toggle button on that menu.
It would just save both of you time so that you both wont have to make that menu. He will be making the menu, you create the toggle button.

**Comment by ngothuythanhtam** [comment]
@pandeyganesha 
Thanks for the update! I love the idea of integrating a pop-up game menu that centralizes settings like the theme toggle, difficulty levels, sound effects, and more. It definitely gives our game a more immersive feel. I can create the theme toggle button for the menu, ensuring it's easy to move and integrate into the pop-up once you have it set up. This way, we can streamline the process and save time. Let me know if you have any specific requirements for the toggle button or if there are any design elements you want me to consider. I'm excited to see how everything comes together!

**Comment by pandeyganesha** [comment]
@ngothuythanhtam For now that is all.
We can always make our game better. Let's see what your creativity brings here.
You can start working on it. Thanks

**Comment by pandeyganesha** [comment]
@ngothuythanhtam 
Thanks, the problem has been solved. Closing the issue.
