### ISSUE TITLE
Theme switch button's ripple effect start from little above the button itself.

### ISSUE THREAD

**Issue by pandeyganesha** [pandeyganesha/digit-dare#12]
When we tap the theme button that toggles between dark and light theme, it does that with ripple animation.
When the button is pressed and ripple expands in circular form until it covers the whole screen. Button the point of origin of that circle must be the toggle button itself.
But currently the center is little above the button.

**Comment by minhb2105709** [comment]
Hi @pandeyganesha , I would like to do this. Can you please assign this issue to me.

**Comment by pandeyganesha** [comment]
Sure @minhb2105709 
Let me know if you understood the task properly or not.

To understand the problem better, you can set the ripple animation speed to something like 10s which makes it very slow and you would be able to see how the center of the ripple's circle is different from the theme switch's button center.


Then center of both must be same.

**Comment by minhb2105709** [comment]
Sure @pandeyganesha 
I think I have a rough understanding of what you mean, I will try to complete it as soon as possible.

**Comment by pandeyganesha** [comment]
@minhb2105709 Thanks for your PR. Closing the issue.
