### ISSUE TITLE
Remove focus from restart button

### ISSUE THREAD

**Issue by pandeyganesha** [pandeyganesha/digit-dare#3]
When we press restart button, the focus for `enter` button remains on it. Means it gets pressed by we press enter. We don't want it.

**Comment by Banh983** [comment]
Hi!, Can you provide more detail about what the problem about, maybe it from a css that caused that problem, you can assgin it to me

**Comment by pandeyganesha** [comment]
@Banh983 
Please once please try to play the game.

- First we enter a five digit number and then press enter, we get the hints.
- then we enter next five digits and hit enter to get the hints and so on.
- when the game ends either by winning or losing, we can press restart button to play again.
- Next time we play and enter five digit number and press enter, we do not get hints, instead the restart button gets pressed again with that `enter` stroke.
- somehow the focus remains on the button when we press it.

The workaround is to press outside once and then all works fine, but I want it to be automatic.
Surely it needs some css fix or some 1-2 liner js.

Go ahead and feel free to fix the issue. Let me know if you need any other detail.
Thanks

**Comment by Banh983** [comment]
Oh i understand the problem,  do you have the link for the repo that have this issue, i would like to see your project code for further adjustment

**Comment by Banh983** [comment]
> Oh i understand the problem, do you have the link for the repo that have this issue, i would like to see your project code for further adjustment

Oh nevermind i see it, gonna work on it now

**Comment by pandeyganesha** [comment]
Thanks @Banh983 
problem solved. Closing the issue. Feel free to contribute and reach out.
