### ISSUE TITLE
Add Difficulty Levels

### ISSUE THREAD

**Issue by pandeyganesha** [pandeyganesha/digit-dare#5]
We plan to add three levels of the game
In level 1 :
- User will be told which of the numbers belongs to the original number but is not at correct place, and which are at correct position
In Level 2:
- User will be given 8-10 attempts to guess the number but will only be told how many numbers are at correct position and how many belongs to the guess but not are at correct position.
In Level 3:
- Same like as Level 2 but will only be given 6 attempts to guess

**Comment by HuyCaoWorkspace** [comment]
Hi @pandeyganesha , I would love to take part in this issue, can you assign this to me?

**Comment by pandeyganesha** [comment]
@HuyCaoWorkspace Sure.

Currently when the page loads, we are showing Game rules.
May be we can replace that with game menu.
Please first update that menu and add the options there for choosing the levels.

Design in a way so that other options like theme toggling could also be inserted there later.
Thanks, let me know if there is any doubt.

**Comment by HuyCaoWorkspace** [comment]
@pandeyganesha took quite some time to figure how to play the game since this game is unfamiliar in my place :)

So if i get your idea correctly, when we first loading the game, a menu will appears instead of rules. In this menu, there're should be 3 components: Rules, Difficulty and Theme (inserted later). In each component interface, there should be the contents, the option to play the game (with level 1 as default) and return to menu, right? Are there any spot that I missed?

**Comment by pandeyganesha** [comment]
@HuyCaoWorkspace Yes you are correct.

For now we have three components only. But we can always add more to it.
We already have got that overlay. In that same space we are going to do this.
Create some minimally animated menu in that space as your own preference.

we can always change the design later. Since this project is in ongoing process we might need to re iterate through our choices and design. For now you got it right. You can start working on it.
Thanks

**Comment by HuyCaoWorkspace** [comment]
hey @pandeyganesha ,I notice that your main branch has some changes, do I need to merge your main?
Another question, in level 1, how many attempts the player have?

**Comment by pandeyganesha** [comment]
@HuyCaoWorkspace 
Yes you need to keep your branch updated with `main` branch before raising PR.
Let's not number the levels and name them 
Easy, medium, Hard. You can choose any other synonyms too.

In easy  there will only be siz attempts but we will also be telling which of the numbers are in correct positions and which are not in correct position but belongs to the answer. Now we only tell how many, not which one.
In easy we would also tell which one.

in medium, we wont tell which one but attempts allowed would be 8. and the Hard will be the one which is now, six attempts.

Let me know if it is clear or not.

**Comment by HuyCaoWorkspace** [comment]
hello @pandeyganesha, I find it quite difficult for me to consider and merge my code with new updates, can i just make a pull request and you decide which code to merge?

**Comment by pandeyganesha** [comment]
@HuyCaoWorkspace Ok go ahead

**Comment by pandeyganesha** [comment]
@HuyCaoWorkspace 
This issue can be closed as the Levels has been added the PR has been accepted. 
Thanks
